### ISSUE TITLE
Bad Build on Mac Os X 10.8.3

### ISSUE THREAD

**Issue by huguesalary** [mozilla-services/heka-build#9]
After running `make`, when the build finishes, running `./bin/hekad` fails:

```
dyld: Symbol not found: _luaopen_base
  Referenced from: /Users/hugues/heka-build/./bin/hekad
  Expected in: /usr/lib/libsandbox.1.dylib
 in /Users/hugues/heka-build/./bin/hekad
```

Running `make test`:

```
mkdir -p release
cd release && cmake .. && make
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/hugues/heka-build/release
[ 72%] Built target lua-5_1_5
[100%] Built target sandbox
-- Install configuration: ""
-- Installing: /Users/hugues/heka-build/bin/libsandbox.dylib
[100%] Built target sandbox_install
./scripts/setup_pluginloader.py
No external plugins loaded for the build.
ok      github.com/mozilla-services/heka/pipeline   0.650s
ok      github.com/mozilla-services/heka/message    0.033s
ok      github.com/mozilla-services/heka/sandbox/lua    0.067s
```

Output of `make`:

```
mkdir -p src/github.com/mozilla-services
cd src/github.com/mozilla-services && \
        git clone https://github.com/mozilla-services/heka.git && \
        cd heka && \
        git submodule update --init --recursive
Cloning into 'heka'...
remote: Counting objects: 4148, done.
remote: Compressing objects: 100% (1848/1848), done.
remote: Total 4148 (delta 2312), reused 4047 (delta 2217)
Receiving objects: 100% (4148/4148), 1.43 MiB | 490 KiB/s, done.
Resolving deltas: 100% (2312/2312), done.
Submodule 'docs/source/_themes/mozilla' (https://github.com/ametaireau/mozilla-sphinx-theme.git) registered for path 'docs/source/_themes/mozilla'
Cloning into 'docs/source/_themes/mozilla'...
remote: Counting objects: 65, done.
remote: Compressing objects: 100% (32/32), done.
remote: Total 65 (delta 35), reused 63 (delta 33)
Unpacking objects: 100% (65/65), done.
Submodule path 'docs/source/_themes/mozilla': checked out '423fb2bd450273a90ed384eca08e4d1dd4dd9736'
mkdir -p release
cd release && cmake .. && make
-- The C compiler identification is Clang 4.2.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/hugues/heka-build/release
Scanning dependencies of target lua-5_1_5
[  9%] Creating directories for 'lua-5_1_5'
[ 18%] Performing download step (download, verify and extract) for 'lua-5_1_5'
-- downloading...
     src='http://www.lua.org/ftp/lua-5.1.5.tar.gz'
     dst='/Users/hugues/heka-build/release/external/src/lua-5.1.5.tar.gz'
     timeout='none'
-- [download 1% complete]
-- [download 2% complete]
-- [download 3% complete]
-- [download 4% complete]
-- [download 5% complete]
-- [download 6% complete]
-- [download 7% complete]
-- [download 8% complete]
-- [download 9% complete]
-- [download 10% complete]
-- [download 11% complete]
-- [download 12% complete]
-- [download 13% complete]
-- [download 14% complete]
-- [download 15% complete]
-- [download 16% complete]
-- [download 17% complete]
-- [download 18% complete]
-- [download 19% complete]
-- [download 20% complete]
-- [download 21% complete]
-- [download 22% complete]
-- [download 23% complete]
-- [download 24% complete]
-- [download 25% complete]
-- [download 26% complete]
-- [download 27% complete]
-- [download 28% complete]
-- [download 29% complete]
-- [download 30% complete]
-- [download 31% complete]
-- [download 32% complete]
-- [download 33% complete]
-- [download 34% complete]
-- [download 35% complete]
-- [download 36% complete]
-- [download 37% complete]
-- [download 38% complete]
-- [download 39% complete]
-- [download 40% complete]
-- [download 41% complete]
-- [download 42% complete]
-- [download 43% complete]
-- [download 44% complete]
-- [download 45% complete]
-- [download 46% complete]
-- [download 47% complete]
-- [download 48% complete]
-- [download 49% complete]
-- [download 50% complete]
-- [download 51% complete]
-- [download 52% complete]
-- [download 53% complete]
-- [download 54% complete]
-- [download 55% complete]
-- [download 56% complete]
-- [download 57% complete]
-- [download 58% complete]
-- [download 59% complete]
-- [download 60% complete]
-- [download 61% complete]
-- [download 62% complete]
-- [download 63% complete]
-- [download 64% complete]
-- [download 65% complete]
-- [download 66% complete]
-- [download 67% complete]
-- [download 68% complete]
-- [download 69% complete]
-- [download 70% complete]
-- [download 71% complete]
-- [download 72% complete]
-- [download 73% complete]
-- [download 74% complete]
-- [download 75% complete]
-- [download 76% complete]
-- [download 77% complete]
-- [download 78% complete]
-- [download 79% complete]
-- [download 80% complete]
-- [download 81% complete]
-- [download 82% complete]
-- [download 83% complete]
-- [download 84% complete]
-- [download 85% complete]
-- [download 86% complete]
-- [download 87% complete]
-- [download 88% complete]
-- [download 89% complete]
-- [download 90% complete]
-- [download 91% complete]
-- [download 92% complete]
-- [download 93% complete]
-- [download 94% complete]
-- [download 95% complete]
-- [download 96% complete]
-- [download 97% complete]
-- [download 98% complete]
-- [download 99% complete]
-- [download 100% complete]
-- downloading... done
-- verifying file...
     file='/Users/hugues/heka-build/release/external/src/lua-5.1.5.tar.gz'
-- verifying file... done
-- extracting...
     src='/Users/hugues/heka-build/release/external/src/lua-5.1.5.tar.gz'
     dst='/Users/hugues/heka-build/release/external/src/lua-5_1_5'
-- extracting... [tar xfz]
-- extracting... [analysis]
-- extracting... [rename]
-- extracting... [clean up]
-- extracting... done
[ 27%] Performing patch step for 'lua-5_1_5'
patching file src/ldebug.c
patching file src/lua.h
Hunk #1 succeeded at 341 (offset 3 lines).
patching file src/Makefile
[ 36%] No update step for 'lua-5_1_5'
[ 45%] No configure step for 'lua-5_1_5'
[ 54%] Performing build step for 'lua-5_1_5'
[ 63%] Performing install step for 'lua-5_1_5'
[ 72%] Completed 'lua-5_1_5'
[ 72%] Built target lua-5_1_5
Scanning dependencies of target sandbox
[ 81%] Building C object src/github.com/mozilla-services/heka/sandbox/CMakeFiles/sandbox.dir/lua/lua_sandbox.c.o
clang: warning: argument unused during compilation: '-shared'
clang: warning: argument unused during compilation: '-flat_namespace'
clang: warning: argument unused during compilation: '-undefined dynamic_lookup'
[ 90%] Building C object src/github.com/mozilla-services/heka/sandbox/CMakeFiles/sandbox.dir/lua/lua_sandbox_private.c.o
clang: warning: argument unused during compilation: '-shared'
clang: warning: argument unused during compilation: '-flat_namespace'
clang: warning: argument unused during compilation: '-undefined dynamic_lookup'
[100%] Building C object src/github.com/mozilla-services/heka/sandbox/CMakeFiles/sandbox.dir/lua/lua_circular_buffer.c.o
clang: warning: argument unused during compilation: '-shared'
clang: warning: argument unused during compilation: '-flat_namespace'
clang: warning: argument unused during compilation: '-undefined dynamic_lookup'
Linking C shared library libsandbox.dylib
clang: warning: argument unused during compilation: '-pthread'
[100%] Built target sandbox
Scanning dependencies of target sandbox_install
-- Install configuration: ""
-- Installing: /Users/hugues/heka-build/bin/libsandbox.dylib
[100%] Built target sandbox_install
./scripts/setup_pluginloader.py
No external plugins loaded for the build.
curl -O https://pypi.python.org/packages/source/v/virtualenv/virtualenv-1.9.1.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 1957k  100 1957k    0     0   707k      0  0:00:02  0:00:02 --:--:--  832k
tar xzvf virtualenv-1.9.1.tar.gz
x virtualenv-1.9.1/
x virtualenv-1.9.1/AUTHORS.txt
x virtualenv-1.9.1/bin/
x virtualenv-1.9.1/bin/rebuild-script.py
x virtualenv-1.9.1/bin/refresh-support-files.py
x virtualenv-1.9.1/docs/
x virtualenv-1.9.1/docs/_theme/
x virtualenv-1.9.1/docs/_theme/nature/
x virtualenv-1.9.1/docs/_theme/nature/static/
x virtualenv-1.9.1/docs/_theme/nature/static/nature.css_t
x virtualenv-1.9.1/docs/_theme/nature/static/pygments.css
x virtualenv-1.9.1/docs/_theme/nature/theme.conf
x virtualenv-1.9.1/docs/conf.py
x virtualenv-1.9.1/docs/index.txt
x virtualenv-1.9.1/docs/make.bat
x virtualenv-1.9.1/docs/Makefile
x virtualenv-1.9.1/docs/news.txt
x virtualenv-1.9.1/LICENSE.txt
x virtualenv-1.9.1/MANIFEST.in
x virtualenv-1.9.1/PKG-INFO
x virtualenv-1.9.1/README.rst
x virtualenv-1.9.1/scripts/
x virtualenv-1.9.1/scripts/virtualenv
x virtualenv-1.9.1/setup.cfg
x virtualenv-1.9.1/setup.py
x virtualenv-1.9.1/virtualenv.egg-info/
x virtualenv-1.9.1/virtualenv.egg-info/dependency_links.txt
x virtualenv-1.9.1/virtualenv.egg-info/entry_points.txt
x virtualenv-1.9.1/virtualenv.egg-info/not-zip-safe
x virtualenv-1.9.1/virtualenv.egg-info/PKG-INFO
x virtualenv-1.9.1/virtualenv.egg-info/SOURCES.txt
x virtualenv-1.9.1/virtualenv.egg-info/top_level.txt
x virtualenv-1.9.1/virtualenv.py
x virtualenv-1.9.1/virtualenv_embedded/
x virtualenv-1.9.1/virtualenv_embedded/activate.bat
x virtualenv-1.9.1/virtualenv_embedded/activate.csh
x virtualenv-1.9.1/virtualenv_embedded/activate.fish
x virtualenv-1.9.1/virtualenv_embedded/activate.ps1
x virtualenv-1.9.1/virtualenv_embedded/activate.sh
x virtualenv-1.9.1/virtualenv_embedded/activate_this.py
x virtualenv-1.9.1/virtualenv_embedded/deactivate.bat
x virtualenv-1.9.1/virtualenv_embedded/distribute_from_egg.py
x virtualenv-1.9.1/virtualenv_embedded/distribute_setup.py
x virtualenv-1.9.1/virtualenv_embedded/distutils-init.py
x virtualenv-1.9.1/virtualenv_embedded/distutils.cfg
x virtualenv-1.9.1/virtualenv_embedded/ez_setup.py
x virtualenv-1.9.1/virtualenv_embedded/site.py
x virtualenv-1.9.1/virtualenv_support/
x virtualenv-1.9.1/virtualenv_support/__init__.py
x virtualenv-1.9.1/virtualenv_support/distribute-0.6.34.tar.gz
x virtualenv-1.9.1/virtualenv_support/pip-1.3.1.tar.gz
x virtualenv-1.9.1/virtualenv_support/setuptools-0.6c11-py2.5.egg
x virtualenv-1.9.1/virtualenv_support/setuptools-0.6c11-py2.6.egg
x virtualenv-1.9.1/virtualenv_support/setuptools-0.6c11-py2.7.egg
mv virtualenv-1.9.1 virtualenv
cd virtualenv && \
    python virtualenv.py ../pythonVE
New python executable in ../pythonVE/bin/python
Installing setuptools............done.
Installing pip...............done.
if [ ! -f /Users/hugues/heka-build/pythonVE/bin/hg ]; \
    then \
        /Users/hugues/heka-build/pythonVE/bin/pip install -U Mercurial; \
    fi
Downloading/unpacking Mercurial
  Downloading mercurial-2.6-rc.tar.gz (3.7MB): 3.7MB downloaded
  Running setup.py egg_info for package Mercurial

Installing collected packages: Mercurial
  Running setup.py install for Mercurial
    warning: hgbuildmo: could not find msgfmt executable, no translations will be built

    building 'mercurial.base85' extension
    cc -fno-strict-aliasing -fno-common -dynamic -I/usr/local/include -I/usr/local/opt/sqlite/include -DNDEBUG -g -O3 -Wall -Wstrict-prototypes -I/usr/local/Cellar/python/2.7.3/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c mercurial/base85.c -o build/temp.macosx-10.8-x86_64-2.7/mercurial/base85.o
    cc -bundle -undefined dynamic_lookup -L/usr/local/lib -L/usr/local/opt/sqlite/lib build/temp.macosx-10.8-x86_64-2.7/mercurial/base85.o -o build/lib.macosx-10.8-x86_64-2.7/mercurial/base85.so
    building 'mercurial.bdiff' extension
    cc -fno-strict-aliasing -fno-common -dynamic -I/usr/local/include -I/usr/local/opt/sqlite/include -DNDEBUG -g -O3 -Wall -Wstrict-prototypes -I/usr/local/Cellar/python/2.7.3/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c mercurial/bdiff.c -o build/temp.macosx-10.8-x86_64-2.7/mercurial/bdiff.o
    cc -bundle -undefined dynamic_lookup -L/usr/local/lib -L/usr/local/opt/sqlite/lib build/temp.macosx-10.8-x86_64-2.7/mercurial/bdiff.o -o build/lib.macosx-10.8-x86_64-2.7/mercurial/bdiff.so
    building 'mercurial.diffhelpers' extension
    cc -fno-strict-aliasing -fno-common -dynamic -I/usr/local/include -I/usr/local/opt/sqlite/include -DNDEBUG -g -O3 -Wall -Wstrict-prototypes -I/usr/local/Cellar/python/2.7.3/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c mercurial/diffhelpers.c -o build/temp.macosx-10.8-x86_64-2.7/mercurial/diffhelpers.o
    cc -bundle -undefined dynamic_lookup -L/usr/local/lib -L/usr/local/opt/sqlite/lib build/temp.macosx-10.8-x86_64-2.7/mercurial/diffhelpers.o -o build/lib.macosx-10.8-x86_64-2.7/mercurial/diffhelpers.so
    building 'mercurial.mpatch' extension
    cc -fno-strict-aliasing -fno-common -dynamic -I/usr/local/include -I/usr/local/opt/sqlite/include -DNDEBUG -g -O3 -Wall -Wstrict-prototypes -I/usr/local/Cellar/python/2.7.3/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c mercurial/mpatch.c -o build/temp.macosx-10.8-x86_64-2.7/mercurial/mpatch.o
    cc -bundle -undefined dynamic_lookup -L/usr/local/lib -L/usr/local/opt/sqlite/lib build/temp.macosx-10.8-x86_64-2.7/mercurial/mpatch.o -o build/lib.macosx-10.8-x86_64-2.7/mercurial/mpatch.so
    building 'mercurial.parsers' extension
    cc -fno-strict-aliasing -fno-common -dynamic -I/usr/local/include -I/usr/local/opt/sqlite/include -DNDEBUG -g -O3 -Wall -Wstrict-prototypes -I/usr/local/Cellar/python/2.7.3/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c mercurial/dirs.c -o build/temp.macosx-10.8-x86_64-2.7/mercurial/dirs.o
    cc -fno-strict-aliasing -fno-common -dynamic -I/usr/local/include -I/usr/local/opt/sqlite/include -DNDEBUG -g -O3 -Wall -Wstrict-prototypes -I/usr/local/Cellar/python/2.7.3/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c mercurial/parsers.c -o build/temp.macosx-10.8-x86_64-2.7/mercurial/parsers.o
    cc -fno-strict-aliasing -fno-common -dynamic -I/usr/local/include -I/usr/local/opt/sqlite/include -DNDEBUG -g -O3 -Wall -Wstrict-prototypes -I/usr/local/Cellar/python/2.7.3/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c mercurial/pathencode.c -o build/temp.macosx-10.8-x86_64-2.7/mercurial/pathencode.o
    cc -bundle -undefined dynamic_lookup -L/usr/local/lib -L/usr/local/opt/sqlite/lib build/temp.macosx-10.8-x86_64-2.7/mercurial/dirs.o build/temp.macosx-10.8-x86_64-2.7/mercurial/parsers.o build/temp.macosx-10.8-x86_64-2.7/mercurial/pathencode.o -o build/lib.macosx-10.8-x86_64-2.7/mercurial/parsers.so
    building 'mercurial.osutil' extension
    cc -fno-strict-aliasing -fno-common -dynamic -I/usr/local/include -I/usr/local/opt/sqlite/include -DNDEBUG -g -O3 -Wall -Wstrict-prototypes -I/usr/local/Cellar/python/2.7.3/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c mercurial/osutil.c -o build/temp.macosx-10.8-x86_64-2.7/mercurial/osutil.o
    cc -bundle -undefined dynamic_lookup -L/usr/local/lib -L/usr/local/opt/sqlite/lib build/temp.macosx-10.8-x86_64-2.7/mercurial/osutil.o -o build/lib.macosx-10.8-x86_64-2.7/mercurial/osutil.so -framework ApplicationServices
    changing mode of build/scripts-2.7/hg from 644 to 755

    changing mode of /Users/hugues/heka-build/pythonVE/bin/hg to 755
Successfully installed Mercurial
Cleaning up...
mkdir -p build
cd build && \
        /Users/hugues/heka-build/pythonVE/bin/hg clone -u 0a4f1eb9372f https://code.google.com/p/go
warning: code.google.com certificate with fingerprint 6a:a6:c5:aa:42:4e:69:f4:34:71:1f:02:c5:dd:a2:05:3f:06:2b:60 not verified (check hostfingerprints or web.cacerts config setting)
destination directory: go
requesting all changes
adding changesets
adding manifests
adding file changes
added 16733 changesets with 59184 changes to 8088 files (+5 heads)
updating to branch default
3723 files updated, 0 files merged, 0 files removed, 0 files unresolved
cd build/go/src && \
        ./all.bash
# Building C bootstrap tool.
cmd/dist

# Building compilers and Go bootstrap tool for host, darwin/amd64.
lib9
libbio
libmach
misc/pprof
cmd/addr2line
cmd/cov
cmd/nm
cmd/objdump
cmd/pack
cmd/prof
cmd/cc
cmd/gc
cmd/6l
cmd/6a
cmd/6c
cmd/6g
pkg/runtime
pkg/errors
pkg/sync/atomic
pkg/sync
pkg/io
pkg/unicode
pkg/unicode/utf8
pkg/unicode/utf16
pkg/bytes
pkg/math
pkg/strings
pkg/strconv
pkg/bufio
pkg/sort
pkg/container/heap
pkg/encoding/base64
pkg/syscall
pkg/time
pkg/os
pkg/reflect
pkg/fmt
pkg/encoding/json
pkg/flag
pkg/path/filepath
pkg/path
pkg/io/ioutil
pkg/log
pkg/regexp/syntax
pkg/regexp
pkg/go/token
pkg/go/scanner
pkg/go/ast
pkg/go/parser
pkg/os/exec
pkg/os/signal
pkg/net/url
pkg/text/template/parse
pkg/text/template
pkg/go/doc
pkg/go/build
cmd/go

# Building packages and commands for darwin/amd64.
runtime
errors
sync/atomic
unicode
unicode/utf8
math
unicode/utf16
crypto/subtle
container/list
container/ring
image/color
sync
io
syscall
hash
crypto/cipher
crypto
hash/crc32
crypto/hmac
hash/adler32
hash/crc64
crypto/md5
crypto/sha1
crypto/sha256
crypto/sha512
bytes
strings
hash/fnv
time
bufio
text/tabwriter
path
html
os
strconv
sort
math/rand
math/cmplx
container/heap
compress/bzip2
path/filepath
os/signal
reflect
regexp/syntax
net/url
os/exec
encoding/base64
crypto/aes
crypto/rc4
encoding/pem
io/ioutil
encoding/ascii85
encoding/base32
image
regexp
image/draw
image/jpeg
fmt
encoding/binary
debug/dwarf
crypto/des
index/suffixarray
flag
go/token
text/template/parse
log
encoding/json
encoding/xml
compress/flate
debug/elf
debug/macho
go/scanner
debug/pe
go/ast
math/big
encoding/hex
compress/gzip
text/template
mime
archive/zip
encoding/gob
runtime/pprof
text/scanner
cmd/yacc
archive/tar
compress/lzw
compress/zlib
database/sql/driver
html/template
debug/gosym
crypto/elliptic
go/doc
go/parser
go/printer
crypto/rand
crypto/dsa
crypto/ecdsa
encoding/asn1
crypto/rsa
database/sql
encoding/csv
image/gif
go/build
crypto/x509/pkix
image/png
runtime/debug
testing
testing/iotest
testing/quick
cmd/cgo
go/format
cmd/gofmt
cmd/fix
cmd/api
cmd/vet
runtime/cgo
net
os/user
crypto/x509
net/textproto
log/syslog
mime/multipart
net/mail
crypto/tls
net/http
net/smtp
cmd/go
expvar
net/http/pprof
net/http/cgi
net/http/cookiejar
net/http/httptest
net/http/httputil
net/rpc
cmd/godoc
net/http/fcgi
net/rpc/jsonrpc

# Testing packages.
ok      cmd/api 0.040s
?       cmd/cgo [no test files]
ok      cmd/fix 0.047s
ok      cmd/go  0.053s
?       cmd/godoc   [no test files]
ok      cmd/gofmt   0.082s
?       cmd/vet [no test files]
?       cmd/yacc    [no test files]
ok      archive/tar 0.027s
ok      archive/zip 0.083s
ok      bufio   0.130s
ok      bytes   0.174s
ok      compress/bzip2  0.100s
ok      compress/flate  0.849s
ok      compress/gzip   0.030s
ok      compress/lzw    0.157s
ok      compress/zlib   1.477s
ok      container/heap  0.151s
ok      container/list  0.048s
ok      container/ring  0.036s
?       crypto  [no test files]
ok      crypto/aes  0.065s
ok      crypto/cipher   0.074s
ok      crypto/des  0.098s
ok      crypto/dsa  0.059s
ok      crypto/ecdsa    0.058s
ok      crypto/elliptic 0.056s
ok      crypto/hmac 0.025s
ok      crypto/md5  0.037s
ok      crypto/rand 0.065s
ok      crypto/rc4  0.133s
ok      crypto/rsa  0.249s
ok      crypto/sha1 0.023s
ok      crypto/sha256   0.025s
ok      crypto/sha512   0.028s
ok      crypto/subtle   0.030s
ok      crypto/tls  0.464s
ok      crypto/x509 1.213s
?       crypto/x509/pkix    [no test files]
ok      database/sql    0.043s
ok      database/sql/driver 0.025s
ok      debug/dwarf 0.031s
ok      debug/elf   0.058s
ok      debug/gosym 0.028s
ok      debug/macho 0.031s
ok      debug/pe    0.060s
ok      encoding/ascii85    0.025s
ok      encoding/asn1   0.035s
ok      encoding/base32 0.027s
ok      encoding/base64 0.027s
ok      encoding/binary 0.031s
ok      encoding/csv    0.050s
ok      encoding/gob    0.089s
ok      encoding/hex    0.026s
ok      encoding/json   0.052s
ok      encoding/pem    0.027s
ok      encoding/xml    0.083s
ok      errors  0.027s
ok      expvar  0.044s
ok      flag    0.027s
ok      fmt 0.069s
ok      go/ast  0.029s
ok      go/build    0.254s
ok      go/doc  0.109s
ok      go/format   0.039s
ok      go/parser   0.080s
ok      go/printer  0.695s
ok      go/scanner  0.030s
ok      go/token    0.086s
?       hash    [no test files]
ok      hash/adler32    0.036s
ok      hash/crc32  0.023s
ok      hash/crc64  0.047s
ok      hash/fnv    0.050s
ok      html    0.061s
ok      html/template   0.097s
ok      image   0.169s
ok      image/color 0.037s
ok      image/draw  0.061s
ok      image/gif   0.028s
ok      image/jpeg  0.234s
ok      image/png   0.086s
ok      index/suffixarray   0.032s
ok      io  0.042s
ok      io/ioutil   0.032s
ok      log 0.033s
ok      log/syslog  2.087s
ok      math    0.047s
ok      math/big    0.305s
ok      math/cmplx  0.022s
ok      math/rand   0.076s
ok      mime    0.046s
ok      mime/multipart  0.451s
ok      net 1.918s
ok      net/http    5.168s
ok      net/http/cgi    0.842s
ok      net/http/cookiejar  0.049s
ok      net/http/fcgi   0.054s
ok      net/http/httptest   0.036s
ok      net/http/httputil   0.050s
?       net/http/pprof  [no test files]
ok      net/mail    0.038s
ok      net/rpc 0.107s
ok      net/rpc/jsonrpc 0.052s
ok      net/smtp    0.043s
ok      net/textproto   0.035s
ok      net/url 0.027s
ok      os  0.083s
ok      os/exec 0.931s
ok      os/signal   0.514s
ok      os/user 0.027s
ok      path    0.023s
ok      path/filepath   0.270s
ok      reflect 0.103s
ok      regexp  0.182s
ok      regexp/syntax   1.024s
ok      runtime 3.813s
?       runtime/cgo [no test files]
ok      runtime/debug   0.023s
ok      runtime/pprof   0.628s
ok      sort    0.099s
ok      strconv 0.537s
ok      strings 0.205s
ok      sync    0.084s
ok      sync/atomic 0.052s
ok      syscall 0.060s
?       testing [no test files]
?       testing/iotest  [no test files]
ok      testing/quick   0.071s
ok      text/scanner    0.026s
ok      text/tabwriter  0.029s
ok      text/template   0.080s
ok      text/template/parse 0.036s
ok      time    2.407s
ok      unicode 0.050s
ok      unicode/utf16   0.048s
ok      unicode/utf8    0.046s
?       unsafe  [no test files]

real    0m22.368s
user    1m50.619s
sys 0m23.557s

# GOMAXPROCS=2 runtime -cpu=1,2,4
ok      runtime 9.689s

# sync -cpu=10
ok      sync    0.098s

# Testing race detector.
ok      flag    1.029s

# ../misc/cgo/stdio

# ../misc/cgo/life

# ../misc/cgo/test
scatter = 0x40022a0
hello from C
PASS
ok      _/Users/hugues/heka-build/build/go/misc/cgo/test    1.133s
scatter = 0xabdad
hello from C
PASS
ok      _/Users/hugues/heka-build/build/go/misc/cgo/test    1.106s
scatter = 0x40022a0
hello from C
PASS
ok      _/Users/hugues/heka-build/build/go/misc/cgo/test    1.134s

# ../doc/progs

real    0m9.940s
user    0m7.564s
sys 0m1.970s

# ../doc/articles/wiki
rm -f srcextract.bin htmlify.bin get.bin
PASS

# ../doc/codewalk

# ../misc/dashboard/builder ../misc/goplay

# ../test/bench/shootout
fasta
reverse-complement
nbody
binary-tree
binary-tree-freelist
fannkuch
fannkuch-parallel
regex-dna
regex-dna-parallel
spectral-norm
k-nucleotide
k-nucleotide-parallel
mandelbrot
meteor-contest
pidigits
threadring
chameneosredux

# ../test/bench/go1
ok      _/Users/hugues/heka-build/build/go/test/bench/go1   2.644s

# ../test

real    0m31.216s
user    1m48.467s
sys 0m35.688s

# Checking API compatibility.
~pkg net, func ListenUnixgram(string, *UnixAddr) (*UDPConn, error)
~pkg text/template/parse, type DotNode bool
~pkg text/template/parse, type Node interface { Copy, String, Type }

ALL TESTS PASSED

---
Installed Go for darwin/amd64 in /Users/hugues/heka-build/build/go
Installed commands in /Users/hugues/heka-build/build/go/bin
*** You need to add /Users/hugues/heka-build/build/go/bin to your PATH.

On OS X the debuggers must be installed setgid procmod.
Read and run ./sudo.bash to install the debuggers.
cp build/go/bin/go /Users/hugues/heka-build/bin/go
Cloning into 'go-simplejson'...

Cloning into 'whisper-go'...

Cloning into 'go-notify'...

Cloning into 'go-msgpack'...

Cloning into 'toml'...

destination directory: go-uuid
requesting all changes
adding changesets
adding manifests
adding file changes
added 10 changesets with 39 changes to 25 files
updating to branch default
14 files updated, 0 files merged, 0 files removed, 0 files unresolved

destination directory: goprotobuf
requesting all changes
adding changesets
adding manifests
adding file changes
added 209 changesets with 785 changes to 94 files
updating to branch default
62 files updated, 0 files merged, 0 files removed, 0 files unresolved
```

**Comment by rafrombrc** [comment]
The build actually worked, but for now you have to make sure the dylib is available on your library path. Easiest way to do this is to run `source bin/activate` from the root of the heka-build folder.

Luckily, it's now possible to statically link Go and C code (see #8) , so very soon there will only be a single binary and this issue will go away.

**Comment by huguesalary** [comment]
Thanks for the quick answer @rafrombrc!
